# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QHadoopTools
                                 A QGIS plugin
 This plugin Spatial Hadoop Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-03
        copyright            : (C) 2021 by Salomón Einstein
        email                : seramirezf@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QHadoopTools class from file QHadoopTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Hadoop_Tools import QHadoopTools
    return QHadoopTools(iface)
