# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QHadoopToolsDialog
                                 A QGIS plugin
 This plugin Spatial Hadoop Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-03
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Salomón Einstein
        email                : seramirezf@correo.udistrital.edu.co
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), "views","copyFromHDFStoLocal.ui"))


class CopyFromHdfsDialog(QtWidgets.QDialog, FORM_CLASS):

    execute_copy = pyqtSignal(dict)
    test_connection = pyqtSignal(dict)
    
    def __init__(self, parent=None):
        """Constructor."""
        super(CopyFromHdfsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)    
        self.btnClear.clicked.connect(self.clear_fields)
        self.btnFindPath.clicked.connect(self.select_file)
        self.btnCopy.clicked.connect(self.run_copy)
        self.btnTest.clicked.connect(self.run_test)
        

    def clear_fields(self):
        self.txtHost.clear()
        self.txtPort.setText("50070")
        self.txtUser.clear()
        self.txtPath.clear()
        self.txtOut.clear()


    def select_file(self):
        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(self, "Select output file")
        if file_path:
            self.txtOut.setText(file_path)



    def get_data(self) -> dict:
        return {
            "connection": {
                "host": self.txtHost.text(),
                "port": int(self.txtPort.text()) if self.txtPort.text() else 50070,
                "user": self.txtUser.text(),
                "protocol": self.cbxProtocol.currentText()
            },
            
            "remote_path": self.txtPath.text(),
            "local_path": self.txtOut.text()
        }
        

    def validate(self) -> None:

        #Normalización
        host = self.txtHost.text().strip()
        port_text = self.txtPort.text().strip()
        remote_path = self.txtPath.text().strip()
        output_path = self.txtOut.text().strip()
        output_path_lower = output_path.lower()
        dir_name = os.path.dirname(output_path)
        protocol = self.cbxProtocol.currentText().lower()
       

        # Host
        if not host:
            raise ValueError("Host is required")

        if " " in host:
            raise ValueError("Host cannot contain spaces")

        if "/" in host:
            raise ValueError("Host cannot contain '/'")

        if ":" in host and not host.startswith("["):
            raise ValueError("Do not include port in host")

        # Port
        if port_text:
            if not port_text.isdigit():
                raise ValueError("Port must be numeric")

            port = int(port_text)
            if port <= 0 or port > 65535:
                raise ValueError("Port must be between 1 and 65535")

        # Remote path (HDFS)
        if not remote_path:
            raise ValueError("HDFS path is required")

        if not remote_path.startswith("/"):
            raise ValueError("HDFS path must start with '/'")

        if " " in remote_path:
            raise ValueError("HDFS path cannot contain spaces")

        # Output file
        if not output_path:
            raise ValueError("Output file is required")
            
        if os.path.isdir(output_path):
            raise ValueError("Output must be a file, not a directory")    

        if dir_name:
            if not os.path.exists(dir_name):
                raise ValueError("Output directory does not exist")

            if not os.path.isdir(dir_name):
                raise ValueError("Output directory is not valid")

        if not output_path_lower.endswith(".geojson"):
            self.txtOut.setText(output_path + ".geojson")

        # Protocol
        if not protocol:
            raise ValueError("Protocol is required")

        if protocol not in ["http", "https"]:
            raise ValueError("Protocol must be 'http' or 'https'")
            
            
            
    def run_copy(self):
        try:
            self.validate()
            data = self.get_data()

            # ✅ emitir datos al controller
            self.execute_copy.emit(data)

        except ValueError as e:
            QtWidgets.QMessageBox.warning(self, "Validation Error", str(e))

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", str(e))

    #def run_copy(self):
    #    self.validate()
    #    self.execute_copy.emit(self.get_data())
    
    
    def run_test(self):
        try:
            data = self.get_data()["connection"]

            if not data["host"]:
                raise ValueError("Host is required")

            if not data["user"]:
                raise ValueError("User is required")

            # ✅ emitir evento
            self.test_connection.emit(data)

        except Exception as e:
            QtWidgets.QMessageBox.warning(
                self,
                "Validation Error",
                str(e)
            )


        

                    


