# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QHadoopToolsDialog
                                 A QGIS plugin
 This plugin Spatial Hadoop Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-03
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Salomón Einstein
        email                : seramirezf@correo.udistrital.edu.co
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
        os.path.dirname(os.path.dirname(__file__)), "views", "copyFromLocalToHDFS.ui"))


class CopyToHdfsDialog(QtWidgets.QDialog, FORM_CLASS):
    
    execute_copy = pyqtSignal(dict)
    test_connection = pyqtSignal(dict)


    def __init__(self, parent=None):
        """Constructor."""
        super(CopyToHdfsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.btnClear.clicked.connect(self.clear_fields)
        self.btnFindPath.clicked.connect(self.select_file)
        self.btnCopy.clicked.connect(self.run_copy)
        self.btnTest.clicked.connect(self.run_test)

        
    def clear_fields(self):
        self.txtHost.clear()
        self.txtPort.setText("50070")
        self.txtUser.clear()
        self.txtPath.clear()
        self.txtIn.clear()


    def select_file(self):
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select input file")
        if file_path:
            self.txtIn.setText(file_path)


    def get_data(self) -> dict:
        return {
            "connection": {
                "host": self.txtHost.text().strip(),
                "port": int(self.txtPort.text()) if self.txtPort.text() else 50070,
                "user": self.txtUser.text().strip(),
                "protocol": self.cbxProtocol.currentText().lower()
            },
            "local_path": self.txtIn.text().strip(),
            "remote_path": self.txtPath.text().strip()
        }


    def validate(self) -> None:

        # Normalización
        host = self.txtHost.text().strip()
        port_text = self.txtPort.text().strip()
        user = self.txtUser.text().strip()
        protocol = self.cbxProtocol.currentText().lower()

        input_path = self.txtIn.text().strip()
        remote_path = self.txtPath.text().strip()

        # Connection
        if not user:
            raise ValueError("User is required")

        if not host:
            raise ValueError("Host is required")

        if " " in host:
            raise ValueError("Host cannot contain spaces")

        if "/" in host:
            raise ValueError("Host cannot contain '/'")

        if "\\" in host:
            raise ValueError("Host cannot contain '\\'")

        if ":" in host and not host.startswith("["):
            raise ValueError("Do not include port in host")

        if port_text:
            if not port_text.isdigit():
                raise ValueError("Port must be numeric")

            port = int(port_text)
            if port <= 0 or port > 65535:
                raise ValueError("Port must be between 1 and 65535")

        if not protocol:
            raise ValueError("Protocol is required")

        if protocol not in ["http", "https"]:
            raise ValueError("Protocol must be 'http' or 'https'")


        # Input (local file)
        if not input_path:
            raise ValueError("Input file is required")

        if not os.path.exists(input_path):
            raise ValueError("Input file does not exist")

        if os.path.isdir(input_path):
            raise ValueError("Input must be a file, not a directory")


        # Target (HDFS path)
        if not remote_path:
            raise ValueError("HDFS path is required")

        if not remote_path.startswith("/"):
            raise ValueError("HDFS path must start with '/'")

        if " " in remote_path:
            raise ValueError("HDFS path cannot contain spaces")
            
        
    def run_copy(self):
        try:
            self.validate()
            data = self.get_data()

            self.execute_copy.emit(data)
            self.accept() 

        except ValueError as e:
            QtWidgets.QMessageBox.warning(self, "Validation Error", str(e))

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", str(e))
        
        
    def run_test(self):
        try:
            data = self.get_data()["connection"]

            if not data["host"]:
                raise ValueError("Host is required")

            if not data["user"]:
                raise ValueError("User is required")

            self.test_connection.emit(data)

        except Exception as e:
            QtWidgets.QMessageBox.warning(
                self,
                "Validation Error",
                str(e)
            )

