# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MostrarNombreDialog
                                 A QGIS plugin
 Muestra nombre de la capa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-08
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Salomón Ramírez / Universidad Distrital
        email                : seramirezf@correo.udistrital.edu.co
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
        os.path.dirname(os.path.dirname(__file__)), "views", "fixJSONtoGeoJSON.ui"))


class FixGeoJsonDialog(QtWidgets.QDialog, FORM_CLASS):

    execute_fix = pyqtSignal(dict)

    def __init__(self, parent=None):
        """Constructor."""
        super(FixGeoJsonDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.btnClear.clicked.connect(self.clear_fields)
        self.btnFindPath.clicked.connect(self.select_input_file)
        self.btnFix.clicked.connect(self.run_fix)


    def clear_fields(self):
        self.txtPath.clear()

        
    def select_input_file(self):
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self,
            "Select JSON file",
            "",
            "JSON files (*.json)"
        )
        if file_path:
            self.txtPath.setText(file_path)


    def get_data(self) -> dict:
        return {
            "input_file": self.txtPath.text().strip()
        }


    def validate(self) -> None:

        input_path = self.txtPath.text().strip()

        if not input_path:
            raise ValueError("Input JSON file is required")

        if input_path.endswith(" "):
            raise ValueError("Invalid input path")

        if not os.path.exists(input_path):
            raise ValueError("Input file does not exist")

        if os.path.isdir(input_path):
            raise ValueError("Input must be a file, not a directory")

        if not input_path.lower().endswith(".json"):
            raise ValueError("Input must be a .json file")
 

    def run_fix(self):
        try:
            self.validate()
            self.execute_fix.emit(self.get_data())
            self.accept() 

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Errror", str(e))




